language: objective-c
osx_image: xcode8
env:
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=10.0,name=iPad Pro (12.9 inch)"

before_script: carthage update

script: xcodebuild test -project Timeline.xcodeproj -scheme Timeline -destination "${DESTINATION}" TOOLCHAINS=swift
