language: objective-c
osx_image: xcode8
env:
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=10.0,name=iPhone 5s"
    - DESTINATION="platform=iOS Simulator,OS=10.0,name=iPhone 6"
    - DESTINATION="platform=iOS Simulator,OS=10.0,name=iPhone 6s Plus"
    - DESTINATION="platform=iOS Simulator,OS=10.0,name=iPad Air"
    - DESTINATION="platform=iOS Simulator,OS=10.0,name=iPad Air 2"
    - DESTINATION="platform=iOS Simulator,OS=10.0,name=iPad Pro (12.9 inch)"
    - DESTINATION="platform=iOS Simulator,OS=10.0,name=iPad Retina"

before_script: carthage update

script: xcodebuild test -project Timeline.xcodeproj -scheme Timeline -destination "${DESTINATION}" TOOLCHAINS=swift

after_success:
  - bash <(curl -s https://codecov.io/bash)
