language: objective-c
osx_image: xcode8
env:
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=10.0,name=iPad Pro (12.9 inch)"

before_script: carthage update

script: xcodebuild test -project DictionaryTools.xcodeproj -scheme DictionaryTools -destination "${DESTINATION}" TOOLCHAINS=swift

after_success:
  - bash <(curl -s https://codecov.io/bash)
